config/routes.rb
Rails.application.routes.draw do
  get 'daily_completed_task/index'

  get 'daily_mail/index'

  get 'tasks_history/index'

  devise_for :users
  get 'pages/home'
  resources :tasks_history

  resources :tasks
  resources :users 
   root 'tasks_history#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Task, user_id: user.id
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
    validates_presence_of :title
    # validates_presence_of :future_completed_date
    # validates_presence_of :user
    # belongs_to :use
    private
    
    def future_completed_date
        if !completed.blank? && completed > Date.today
            self.errors.add(:completed , "can't be in the future")
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

end

app/controllers/daily_completed_task_controller.rb
class DailyCompletedTaskController < ApplicationController
  def index
    complete = Task.where.not(completed: nil).pluck(:id)
    @completed = Task.where(id: complete).order(completed: :desc)
        
  end
end

app/controllers/daily_mail_controller.rb
class DailyMailController < ApplicationController
    
    def index
        require 'gmail'
        pending = Task.where(completed: nil)
        complete = Task.where.not(completed: nil).pluck(:id)
        completed = Task.where(id: complete ).order(completed: :desc)
        pending_body_content = ""
        pending.each do |i|
            pending_body_content += " - #{i.title}  \n"
        end
        completed_body_content = ""
        completed.each do |c|
            completed_body_content += "- #{c.title} \n"
  
        end
        user_name = 'kyony.j@infoset.cd'
        password  = 'f@cus1sbr1ght21'
        gmail = Gmail.new(user_name,password) 
        gmail.deliver do 
            to "kanyinda.a@infoset.cd"
            subject "Daily report"
            text_part do 
                body "Hi Arnold Here is the summary of the daily task of #{Date.today} \n This are the following task that are completed \n #{completed_body_content} \n This is the pending task \n #{pending_body_content} " 
                    
            end
        end
        
        redirect_to root_path
                        
                
            
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
   @tasks = Task.all.order(created_at: :desc)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    render :show_form
  end

  def create
    @task = Task.new(task_params)
    save_task
  end

  def edit
    @task = Task.find(params[:id])
   
    render :show_form
  end

  def update
    @task = Task.find(params[:id])
    @task.assign_attributes(task_params)
    
    save_task
  end

  def destroy
    @task = Task.find(params[:id])
   
    @task.destroy
    @tasks = Task.all
  end

  private

  def save_task
    if @task.save
      @tasks = Task.all
      render :hide_form
    else
      render :show_form
    end
  end

  def task_params
    params.require(:task).permit(:title, :note, :completed)
  end
end

app/controllers/tasks_history_controller.rb
class TasksHistoryController < ApplicationController
  def index
    @task_history = Task.where(completed: nil)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_completed_task_helper.rb
module DailyCompletedTaskHelper
end

app/helpers/daily_mail_helper.rb
module DailyMailHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tasks_history_helper.rb
module TasksHistoryHelper
end

app/views/daily_completed_task/index.html.haml
.container 
  .col-md-12
    - if @completed.empty?
      %span.text-warning There are no tasks!
    - else
      %table.table.table-hover.table-bordered
        %thead
          %tr
            %th Title
            %th Created at
            %th Completed
            %th Actions
        %tbody
          - @completed.each do |task|
            %tr
              %td
                %strong= task.title
              %td.text-info= task.created_at
              %td.text-success= task.completed
              %td
                = link_to task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete task #{task.title}?"} do
                  %i.glyphicon.glyphicon-remove
                = link_to edit_task_path(task), remote: true do
                  %i.glyphicon.glyphicon-pencil

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Infoset Todo 
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==", crossorigin: "anonymous"}
    %script{src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js", integrity: "sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==", crossorigin: "anonymous"}
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{:role => "navigation"}
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{"data-target" => "#navbar-brand-centered", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-brand.navbar-brand-centered Infoset
        / Collect the nav links, forms, and other content for toggling
        #navbar-brand-centered.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Pending" , tasks_history_index_path
           
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown" , :href => "#"} History
               
              %ul.dropdown-menu
                %li 
                  = link_to 'Completed task' , daily_completed_task_index_path
                %li
                  = link_to 'All' , pages_home_path
            
               
               
            
           
           
        
    .container
      .row
        .col-md-8.col-md-offset-3
          .jumbotron.text-center
           
            %h1
              
              %small My Infoset Task manager
            - if current_user
              .text-center
                = link_to 'New task' , new_task_path , class: 'btn btn-primary ' , remote: true
                = link_to 'Daily Mail' , daily_mail_index_path , class: 'btn btn-primary'
            
              .text-center
                %strong= current_user.email
          
              .text-center
                = link_to 'logout' , destroy_user_session_path , method: :delete
              
    .container            
      .row-fluid
        .col-md-4.offset4
          #modal.modal.fade{:role => "dialog" , :tabindex => "1"}
          = yield
           
   

app/views/pages/home.html.haml
.container#task-list
  .row
    .col-md-12
      = render partial: 'tasks/task_list' , locals: {tasks: @tasks}

#modal.modal.fade{:role => "dialog", :tabindex => "-1"}

app/views/shared/_flash.html.haml
- flash.each do |type , value|
  .flash{ :class => type.to_s}
    = value

app/views/tasks/_task_form.html.haml
.modal-dialog
  .modal-content

    .modal-header
      %h1
        = task.new_record? ? 'New Task' : "Editing task #{task.title}" 
    = simple_form_for task , class: 'clearfix' , remote: true do |f|
      .modal-body
        = f.input :title
        = f.input :note
        = f.input :completed , as: :string , input_html: {"data-provide" => "datepicker"}
      .modal-footer
        = f.submit 'Save' , class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
.container
- if tasks.empty?
  %span.text-warning There are no tasks!
- else
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th Title
        %th Created at
        %th Completed
        %th Actions
    %tbody
      - tasks.each do |task|
        %tr
          %td
            %strong= task.title
          %td.text-info= task.created_at
          %td.text-success= task.completed
          %td
            = link_to task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete task #{task.title}?"} do
              %i.glyphicon.glyphicon-remove
            = link_to edit_task_path(task), remote: true do
              %i.glyphicon.glyphicon-pencil

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>');

app/views/tasks/hide_form.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task})%>');﻿
m.modal('show');
$('#modal').integrateDatepicker();

app/views/tasks_history/index.html.haml
.container 
  .col-md-12
    - if @task_history.empty?
      %span.text-warning There are no tasks!
    - else
      %table.table.table-hover.table-bordered
        %thead
          %tr
            %th Title
            %th Created at
            %th Completed
            %th Actions
        %tbody
          - @task_history.each do |task|
            %tr
              %td
                %strong= task.title
              %td.text-info= task.created_at
              %td.text-success= task.completed
              %td
                = link_to task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete task #{task.title}?"} do
                  %i.glyphicon.glyphicon-remove
                = link_to edit_task_path(task), remote: true do
                  %i.glyphicon.glyphicon-pencil